import re
import requests

urls = [
    "https://www.python.org",
    "https://www.wikipedia.org",
    "https://www.github.com",
    "https://www.stackoverflow.com",
    "https://www.reddit.com",
    "https://www.mozilla.org",
    "https://www.w3schools.com",
    "https://www.geeksforgeeks.org",
    "https://realpython.com",
    "https://www.freecodecamp.org",
    "https://www.openai.com",
    "https://www.microsoft.com",
    "https://www.apple.com",
    "https://www.google.com",
    "https://www.bing.com",
    "https://www.yahoo.com",
    "https://www.amazon.com",
    "https://store.steampowered.com",
    "https://www.epicgames.com",
    "https://www.gog.com",
    "https://www.nasa.gov",
    "https://www.nationalgeographic.com",
    "https://www.bbc.com",
    "https://www.cnn.com",
    "https://www.reuters.com",
    "https://www.nytimes.com",
    "https://www.theguardian.com",
    "https://www.imdb.com",
    "https://www.rottentomatoes.com",
    "https://www.netflix.com",
    "https://www.disneyplus.com",
    "https://www.spotify.com",
    "https://www.youtube.com",
    "https://www.twitch.tv",
    "https://www.instagram.com",
    "https://www.facebook.com",
    "https://www.linkedin.com",
    "https://www.x.com",
    "https://www.pinterest.com",
    "https://www.quora.com",
    "https://www.canva.com",
    "https://www.figma.com",
    "https://www.dropbox.com",
    "https://www.cloudflare.com",
    "https://www.digitalocean.com",
    "https://www.heroku.com",
    "https://www.jetbrains.com",
    "https://www.oracle.com",
    "https://www.ibm.com",
    "https://www.intel.com",
    "https://www.amd.com",
    "https://www.nvidia.com",
    "https://www.lenovo.com",
    "https://www.hp.com",
    "https://www.dell.com",
    "https://www.asus.com",
    "https://www.acer.com",
    "https://www.samsung.com",
    "https://www.sony.com",
    "https://www.lg.com",
    "https://www.adobe.com",
    "https://www.paypal.com",
    "https://www.stripe.com",
    "https://www.airbnb.com",
    "https://www.booking.com",
    "https://www.expedia.com",
    "https://www.tripadvisor.com",
    "https://www.uber.com",
    "https://www.lyft.com",
    "https://www.zoom.us",
    "https://slack.com",
    "https://trello.com",
    "https://asana.com",
    "https://notion.so",
    "https://clickup.com",
    "https://medium.com",
    "https://dev.to",
    "https://hashnode.com",
    "https://codeforces.com",
    "https://leetcode.com",
    "https://www.hackerrank.com",
    "https://www.codechef.com",
    "https://atcoder.jp",
    "https://www.kaggle.com",
    "https://www.tensorflow.org",
    "https://pytorch.org",
    "https://numpy.org",
    "https://pandas.pydata.org",
    "https://matplotlib.org",
    "https://scikit-learn.org",
    "https://flask.palletsprojects.com",
    "https://www.djangoproject.com",
    "https://fastapi.tiangolo.com",
    "https://docs.python.org",
    "https://docs.github.com",
    "https://developer.mozilla.org",
    "https://news.ycombinator.com",
    "https://archive.org",
    "https://www.gnu.org",
    "https://ubuntu.com",
    "https://www.debian.org",
    "https://kernel.org",
    "https://www.raspberrypi.com",
]
with open(
    "Task3(Task Automation with Python Scripts)/Scrape a webpage title/title.txt",
    "w",
) as f:
    for url in urls:
        try :
            response = requests.get(url,timeout=2)
            if response.status_code == 200:
                title = re.search(r"<title>(.*?)</title>", response.text)
                if title:
                    print(title.group(1))
                    f.write(title.group(1) + "\n")
            
            print(f"Failed to fetch the webpage{url} ")

        except requests.exceptions.RequestException as e :
            print (f"Error excessing {url}")
            print (e)

print("Title Saved successfully")
